### ISSUE TITLE
Move back button and deviceready handler code from main.js to App.vue

### ISSUE THREAD

**Issue by hollyschinsky** [phonegap/phonegap-template-vue-f7-split-panel#11] opened 2017-11-09 05:04 UTC
Move the https://github.com/phonegap/phonegap-template-vue-f7-split-panel/blob/master/template/src/main.js#L65-L89 block into App.vue

**Comment by devgeeks** [comment] 2017-11-15 00:31
Dupe of #8 ?

**Closed by devgeeks** 2017-11-15 00:31 UTC
Labels: duplicate
